Irrigation test system 1: src/hw.h File Reference
hw.h File Reference
Hardware abstraction layer include file.
Macros
#define DEFAULT(value, default) value = value ? value : default
Sets a value if the value evaluates to false.
#define VREF 3.295
#define R1 100000.0
#define NTC_R 150000
#define NTC_A1 3.354016E-03
#define NTC_B1 2.367720E-04
#define NTC_C1 3.585140E-06
#define NTC_D1 1.255349E-07
#define T0_K 273.15
#define PWM_PERIOD 4096
#define PWM_TOP (PWM_PERIOD - 1)
#define _HW_H_
Enumerations
enum hw_init_state {
HW_INIT_UNINITIALIZED, HW_INIT_RCC, HW_INIT_GPIO, HW_INIT_PRE_NVIC,
HW_INIT_NVIC, HW_INIT_POST_INIT, HW_INIT_INITIALIZED
}
This is the state of the hardware abstraction layer.
Functions
void hw_init ()
Call hw_init_state with all states to go trough.
void hw_init_state (enum hw_init_state state)
This function prototype calls all perhipherals with the state as argument.
Detailed Description
Hardware abstraction layer include file.
Todo:
There is some stuff not belonging to this file in here, it should be moved
The hardware abstraction layer should be completely generic except that it initializes the system in a predefined order
Definition in file hw.h.
Macro Definition Documentation
#define DEFAULT (value, default) value = value ? value : default
Sets a value if the value evaluates to false.
Parameters
value Variable to check and possibly set
default Default value if value was 0
Definition at line 15 of file hw.h.
Referenced by timer_ccr_init(), usart_configure_gpio(), usart_set_defaults(), ws2812_configure_gpio(), ws2812_configure_timer(), and ws2812_set_defaults().
Enumeration Type Documentation
enum hw_init_state
This is the state of the hardware abstraction layer.
Enumerator
HW_INIT_UNINITIALIZED
Hardware is not initialized.
HW_INIT_RCC
This is the first state entered and here hardware drivers may initialize any clocks needed.
HW_INIT_GPIO
After clocks have been initialized all GPIO will be initialized, this also puts pins to their default value)
HW_INIT_PRE_NVIC
After GPIOs have been initialized we might want to do some stuff before NVIC.
Todo:
Implement the default value thing
HW_INIT_NVIC
After GPIO have been initialized all NVIC will be initialized.
HW_INIT_POST_INIT
After NVIC is initialized there might be more stuff todo such as setting up perhipheral settings.
Definition at line 33 of file hw.h.
Function Documentation
void hw_init ()
Call hw_init_state with all states to go trough.
Definition at line 18 of file hw.c.
References HW_INIT_GPIO, HW_INIT_NVIC, HW_INIT_POST_INIT, HW_INIT_PRE_NVIC, and HW_INIT_RCC.
Referenced by main().
void hw_init_state (enum hw_init_state state)
This function prototype calls all perhipherals with the state as argument.
This function prototype calls all perhipherals with the state as argument.
Definition at line 64 of file main.c.
References usart_init(), and ws2812_init().