Irrigation test system 1: src/main.c File Reference
main.c File Reference
Irrigation controller main file.
#include "math.h"
#include "ws2812_macro.h"
#include "usart_macro.h"
#include "led_macro.h"
#include "timer_macro.h"
#include "systick.h"
#include "adc.h"
#include "time.h"
#include "filter.h"
#include "irrigation.h"
Classes
struct state
Macros
#define NTC_Filter_Size 250
Functions
GPIO_PORT_INSTANCE (GPIO_PA, GPIOA, RCC_GPIOA)
GPIO_PORT_INSTANCE (GPIO_PB, GPIOB, RCC_GPIOB)
WS2812_INSTANCE (StatusLED, TIMER1_CCR3N_DMA,&GPIO_PB, GPIO15, 1)
USART_TXONLY_INSTANCE (Serial, USART1, RCC_USART1, 921600, 0, 0, 0, 0,&GPIO_PA, GPIO_USART1_TX)
TIMER_CCR_INSTANCE (Pump,&GPIO_PB, GPIO_MODE_OUTPUT_2_MHZ, GPIO_CNF_OUTPUT_ALTFN_PUSHPULL, GPIO0, TIMER3_CCR3, 4095, 0)
TIMER_CCR_INSTANCE (Heater,&GPIO_PA, GPIO_MODE_OUTPUT_2_MHZ, GPIO_CNF_OUTPUT_ALTFN_PUSHPULL, GPIO2, TIMER2_CCR3, 4095, 0)
GAMMA_LUT_8_8_E_INSTANCE (LED_Gamma)
GPIO_PIN_INSTANCE (NTC_pin,&GPIO_PA, GPIO_MODE_INPUT, GPIO_CNF_INPUT_ANALOG, GPIO3)
void hw_init_state (enum hw_init_state state)
This function prototype calls all perhipherals with the state as argument.
void sys_tick_handler (void)
void get_system_time_blocking (struct sw_timer_system_time *result)
void dma1_channel1_isr (void)
void status_color (int r, int g, int b)
Set color of indicator LED.
void usart_blocking_tm (struct usart *usart, struct sw_timer_system_time *tm)
Send broken down time using blocking/polling (no dma/irq)
struct state * get_state (enum irrigation_status status)
void report_current_temperature (struct irrigation_controller *controller)
Reports current temperature.
void report_validation_temperatures (struct irrigation_controller *controller)
Report the measured temperatures for validation.
void report_sensor_malfunction (struct irrigation_controller *controller)
Report that sensordata is invalid.
void report_sensor_fluctuations (struct irrigation_controller *controller)
Report that sensordata fluctuates.
void report_msg_note (struct irrigation_controller *controller, char *msg)
Generic note as a string, used for debugging.
void report_measurement_data (struct irrigation_controller *controller, char *msg)
Report water content data.
Variables
struct systick_config Systick_config
struct systick Systick
struct adc_config NTC_adc_config
uint16_t NTC_buffer [1]
struct adc NTC_adc
volatile uint32_t NTC_filter_buffer [NTC_Filter_Size]
struct filter_rms NTC_filter
volatile int sleep_ms = 0
volatile int NTC_filtered_value = -1
volatile struct sw_timer_system_time system_time = {1420070400, 0}
volatile bool system_time_updated =0
const struct state state_init = {state_init_enter, state_init_run, state_init_exit, "Init"}
const struct state state_validate = {state_validate_enter, state_validate_run, state_validate_exit, "Validate temperature sensor"}
const struct state state_reboot = {state_reboot_enter, state_reboot_run, state_reboot_exit, "Reboot"}
const struct state state_measure = {state_measure_enter, state_measure_run, state_measure_exit, "Measure soil water content"}
struct irrigation_controller ic
This is the main irrigation controller state.
Detailed Description
Irrigation controller main file.
Todo:
systick, adc, moisture sensor, pwm output, filter
Definition in file main.c.
Function Documentation
void hw_init_state (enum hw_init_state state)
This function prototype calls all perhipherals with the state as argument.
Definition at line 75 of file main.c.
References timer_ccr_init(), usart_init(), and ws2812_init().
void report_current_temperature (struct irrigation_controller * controller)
Reports current temperature.
Definition at line 339 of file main.c.
References irrigation_controller_status::iteration_time, irrigation_controller_status::soil_temperature, irrigation_controller::status, irrigation_temperature_sample::temperature, usart_blocking_float(), usart_blocking_str, and usart_blocking_tm().
void report_measurement_data (struct irrigation_controller * controller, char * msg)
Report water content data.
Definition at line 379 of file main.c.
References irrigation_controller_status::iteration_time, irrigation_controller::status, usart_blocking_float(), usart_blocking_str, and usart_blocking_tm().
void report_msg_note (struct irrigation_controller * controller, char * msg)
Generic note as a string, used for debugging.
Definition at line 371 of file main.c.
References irrigation_controller_status::iteration_time, irrigation_controller::status, usart_blocking_str, usart_blocking_strz(), and usart_blocking_tm().
void report_sensor_fluctuations (struct irrigation_controller * controller)
Report that sensordata fluctuates.
Definition at line 365 of file main.c.
References irrigation_controller_status::iteration_time, irrigation_controller::status, usart_blocking_str, and usart_blocking_tm().
void report_sensor_malfunction (struct irrigation_controller * controller)
Report that sensordata is invalid.
Definition at line 359 of file main.c.
References irrigation_controller_status::iteration_time, irrigation_controller::status, usart_blocking_str, and usart_blocking_tm().
void report_validation_temperatures (struct irrigation_controller * controller)
Report the measured temperatures for validation.
See also
state_validate_enter min_temperature max_temperature
Definition at line 347 of file main.c.
References irrigation_controller_status::iteration_time, irrigation_controller_status::max_temperature, irrigation_controller_status::min_temperature, irrigation_controller::status, usart_blocking_float(), usart_blocking_str, and usart_blocking_tm().
void status_color (int r, int g, int b)
Set color of indicator LED.
Todo:
Move this to the events API
Definition at line 150 of file main.c.
Referenced by state_init_run(), and state_validate_run().
void usart_blocking_tm (struct usart * usart, struct sw_timer_system_time * tm)
Send broken down time using blocking/polling (no dma/irq)
Definition at line 289 of file main.c.
References sw_timer_system_time::epoch, sw_timer_system_time::ms, time_tm_from_epoch(), tm::tm_hour, tm::tm_mday, tm::tm_min, tm::tm_mon, tm::tm_sec, tm::tm_year, usart_blocking_int(), usart_blocking_int_zp(), and usart_blocking_str.
Referenced by report_current_temperature(), report_measurement_data(), report_msg_note(), report_sensor_fluctuations(), report_sensor_malfunction(), and report_validation_temperatures().
Variable Documentation
struct irrigation_controller ic
Initial value:
= {
    .events = {
        .report_validation_temperatures = report_validation_temperatures,
        .report_sensor_malfunction = report_sensor_malfunction,
        .report_sensor_fluctuations = report_sensor_fluctuations,
        .report_current_temperature = report_current_temperature,
        .report_msg_note = report_msg_note,
        .report_measurement_data = report_measurement_data,
    }
}
This is the main irrigation controller state.
Definition at line 391 of file main.c.
struct adc NTC_adc
Initial value:
= {
    .configuration = &NTC_adc_config,
    .adc_buffer = NTC_buffer,
}
Definition at line 51 of file main.c.
struct adc_config NTC_adc_config
Initial value:
= {
    .channel_map = &(uint8_t){3},
    .channel_count = 1,
}
Definition at line 44 of file main.c.
struct filter_rms NTC_filter
Initial value:
= {
    .buffer = NTC_filter_buffer,
    .size = NTC_Filter_Size,
    .valid_range = {
        .min = 1200,
        .max = 3400,
    },
}
Definition at line 61 of file main.c.
struct systick Systick
Initial value:
= {
    .configuration = &Systick_config,
}
Definition at line 39 of file main.c.
struct systick_config Systick_config
Initial value:
= {
    .frequency = 1000,
    .auto_start = 1,
}
Definition at line 34 of file main.c.