Irrigation test system 1: irrigation_events Struct Reference
irrigation_events Struct Reference
The event callback functions for the irrigation controller core.
#include <irrigation.h>
Public Attributes
void(* report_validation_temperatures)(struct irrigation_controller *)
Report the measured temperatures for validation.
void(* report_sensor_malfunction)(struct irrigation_controller *)
Report that sensordata is invalid.
void(* report_sensor_fluctuations)(struct irrigation_controller *)
Report that sensordata fluctuates.
void(* report_current_temperature)(struct irrigation_controller *)
Reports current temperature.
void(* report_measurement_data)(struct irrigation_controller *)
Report water content data.
void(* report_msg_note)(struct irrigation_controller *, char *)
Generic note as a string, used for debugging.
Detailed Description
The event callback functions for the irrigation controller core.
Definition at line 71 of file irrigation.h.
Member Data Documentation
void(* irrigation_events::report_current_temperature) (struct irrigation_controller *)
Reports current temperature.
Definition at line 75 of file irrigation.h.
void(* irrigation_events::report_measurement_data) (struct irrigation_controller *)
Report water content data.
Definition at line 76 of file irrigation.h.
void(* irrigation_events::report_msg_note) (struct irrigation_controller *, char *)
Generic note as a string, used for debugging.
Definition at line 77 of file irrigation.h.
Referenced by state_measure_enter().
void(* irrigation_events::report_sensor_fluctuations) (struct irrigation_controller *)
Report that sensordata fluctuates.
Definition at line 74 of file irrigation.h.
Referenced by state_validate_run().
void(* irrigation_events::report_sensor_malfunction) (struct irrigation_controller *)
Report that sensordata is invalid.
Definition at line 73 of file irrigation.h.
Referenced by state_measure_enter(), state_validate_enter(), and state_validate_run().
void(* irrigation_events::report_validation_temperatures) (struct irrigation_controller *)
Report the measured temperatures for validation.
See also
state_validate_enter min_temperature max_temperature
Definition at line 72 of file irrigation.h.
Referenced by state_validate_run().
The documentation for this struct was generated from the following file:
src/irrigation.h