Irrigation test system 1: src/timer.c File Reference
timer.c File Reference
Timer HAL implementation.
#include "timer.h"
Functions
void timer_ccr_init (struct timer_ccr *ccr, enum hw_init_state state)
Upgrade timer_ccr state and init hardware.
void timer_ccr_set (struct timer_ccr *ccr, uint32_t value)
Set CCR value of timer_ccr.
void timer_init (struct timer *timer, enum hw_init_state state)
Upgrade timer_init state and init hardware.
Detailed Description
Timer HAL implementation.
Definition in file timer.c.
Function Documentation
void timer_ccr_init (struct timer_ccr * ccr, enum hw_init_state state)
Upgrade timer_ccr state and init hardware.
Todo:
Add more CCR-channels
Todo:
Only upgrade state if needed
Definition at line 12 of file timer.c.
References DEFAULT, HW_INIT_PRE_NVIC, HW_INIT_RCC, and timer_init().
Referenced by ws2812_init().
void timer_ccr_set (struct timer_ccr * ccr, uint32_t value)
Set CCR value of timer_ccr.
Definition at line 79 of file timer.c.
void timer_init (struct timer * timer, enum hw_init_state state)
Upgrade timer_init state and init hardware.
Definition at line 84 of file timer.c.
References HW_INIT_POST_INIT, HW_INIT_PRE_NVIC, and HW_INIT_RCC.
Referenced by timer_ccr_init().