Irrigation test system 1: src/timer.h File Reference
timer.h File Reference
Timer HAL include file.
#include "hw.h"
#include <libopencm3/stm32/timer.h>
#include <libopencm3/stm32/rcc.h>
#include "dma.h"
Classes
struct timer_ccr_config
struct timer_ccr
struct timer_config
struct timer
Functions
void timer_ccr_init (struct timer_ccr *ccr, enum hw_init_state state)
Upgrade timer_ccr state and init hardware.
void timer_init (struct timer *timer, enum hw_init_state state)
Upgrade timer_init state and init hardware.
void timer_ccr_set (struct timer_ccr *ccr, uint32_t value)
Set CCR value of timer_ccr.
Detailed Description
Timer HAL include file.
Definition in file timer.h.
Function Documentation
void timer_ccr_init (struct timer_ccr * ccr, enum hw_init_state state)
Upgrade timer_ccr state and init hardware.
Todo:
Add more CCR-channels
Todo:
Only upgrade state if needed
Definition at line 12 of file timer.c.
References DEFAULT, HW_INIT_PRE_NVIC, HW_INIT_RCC, and timer_init().
Referenced by ws2812_init().
void timer_ccr_set (struct timer_ccr * ccr, uint32_t value)
Set CCR value of timer_ccr.
Definition at line 79 of file timer.c.
void timer_init (struct timer * timer, enum hw_init_state state)
Upgrade timer_init state and init hardware.
Definition at line 84 of file timer.c.
References HW_INIT_POST_INIT, HW_INIT_PRE_NVIC, and HW_INIT_RCC.
Referenced by timer_ccr_init().