Irrigation test system 1: src/uart.h File Reference
uart.h File Reference
UART HAL Include file.
#include "gpio.h"
#include "time.h"
#include <libopencm3/stm32/usart.h>
Classes
struct usart_config
Usart configuration.
struct usart
Usart.
Macros
#define usart_blocking_str(uart, str) usart_blocking_send(uart, str, sizeof(str)-1)
Send string literal using blocking/polling (no dma or irq)
#define _UART_H_
Functions
void usart_init (struct usart *usart, enum hw_init_state state)
Init usart device.
void usart_blocking_send (struct usart *usart, volatile void *data, int length)
Send data using blocking/polling method (no IRQ nor DMA)
void usart_blocking_float (struct usart *usart, float data)
Send a formatted float using blocking/polling method (no IRQ nor DMA)
void usart_blocking_int (struct usart *usart, int data)
Send formatted integer using blocking/polling method (no IRQ nor DMA)
void usart_blocking_int_zp (struct usart *usart, int data, int dp)
Send a formatted int with zeropadding using blocking/polling method (no IRQ nor DMA)
void usart_blocking_strz (struct usart *usart, volatile char *data)
Send zero terminated string using blocking/polling method (no IRQ nor DMA)
void usart_blocking_tm (struct usart *usart, struct sw_timer_system_time *tm)
Send broken down time using blocking/polling (no dma/irq)
Detailed Description
UART HAL Include file.
Definition in file uart.h.
Macro Definition Documentation
#define usart_blocking_str (uart, str) usart_blocking_send(uart, str, sizeof(str)-1)
Send string literal using blocking/polling (no dma or irq)
Definition at line 11 of file uart.h.
Referenced by main(), and usart_blocking_tm().
Function Documentation
void usart_blocking_float (struct usart * usart, float data)
Send a formatted float using blocking/polling method (no IRQ nor DMA)
Parameters
usart Pointer to USART device
data Floating point value to format and send
Definition at line 137 of file usart.c.
References usart_blocking_int(), and usart_blocking_int_zp().
void usart_blocking_int (struct usart * usart, int data)
Send formatted integer using blocking/polling method (no IRQ nor DMA)
Definition at line 90 of file usart.c.
Referenced by usart_blocking_float(), and usart_blocking_tm().
void usart_blocking_int_zp (struct usart * usart, int data, int dp)
Send a formatted int with zeropadding using blocking/polling method (no IRQ nor DMA)
Parameters
usart Pointer to USART device
data Integer value to format and send
dp Number of digits to use
pow() takes like 4kb of flash so avoid it here since we are just working with integers anyway
Definition at line 114 of file usart.c.
Referenced by usart_blocking_float(), and usart_blocking_tm().
void usart_blocking_send (struct usart * usart, volatile void * data, int length)
Send data using blocking/polling method (no IRQ nor DMA)
Definition at line 71 of file usart.c.
void usart_blocking_strz (struct usart * usart, volatile char * data)
Send zero terminated string using blocking/polling method (no IRQ nor DMA)
Definition at line 82 of file usart.c.
void usart_blocking_tm (struct usart * usart, struct sw_timer_system_time * tm)
Send broken down time using blocking/polling (no dma/irq)
Definition at line 146 of file usart.c.
References sw_timer_system_time::epoch, sw_timer_system_time::ms, time_tm_from_epoch(), tm::tm_hour, tm::tm_mday, tm::tm_min, tm::tm_mon, tm::tm_sec, tm::tm_year, usart_blocking_int(), usart_blocking_int_zp(), and usart_blocking_str.
Referenced by main().
void usart_init (struct usart * usart, enum hw_init_state state)
Init usart device.
Todo:
Check if we are inited already
Definition at line 38 of file usart.c.
References HW_INIT_POST_INIT, HW_INIT_PRE_NVIC, HW_INIT_RCC, usart_configure_gpio(), and usart_set_defaults().
Referenced by hw_init_state().