Irrigation test system 1: src/usart.c File Reference
usart.c File Reference
USART HAL driver.
#include "uart.h"
#include <math.h>
Functions
void usart_set_defaults (struct usart *usart)
Configure USART to default values.
void usart_configure_gpio (struct usart *usart)
Configure USART GPIO default values.
void usart_init (struct usart *usart, enum hw_init_state state)
Init usart device.
void usart_blocking_send (struct usart *usart, volatile void *data, int length)
Send data using blocking/polling method (no IRQ nor DMA)
void usart_blocking_strz (struct usart *usart, volatile char *ptr)
Send zero terminated string using blocking/polling method (no IRQ nor DMA)
void usart_blocking_int (struct usart *usart, int data)
Send formatted integer using blocking/polling method (no IRQ nor DMA)
void usart_blocking_int_zp (struct usart *usart, int data, int dp)
Send a formatted int with zeropadding using blocking/polling method (no IRQ nor DMA)
void usart_blocking_float (struct usart *usart, float data)
Send a formatted float using blocking/polling method (no IRQ nor DMA)
Detailed Description
USART HAL driver.
Definition in file usart.c.
Function Documentation
void usart_blocking_float (struct usart * usart, float data)
Send a formatted float using blocking/polling method (no IRQ nor DMA)
Parameters
usart Pointer to USART device
data Floating point value to format and send
Definition at line 128 of file usart.c.
References usart_blocking_int(), and usart_blocking_int_zp().
Referenced by report_current_temperature(), report_measurement_data(), and report_validation_temperatures().
void usart_blocking_int (struct usart * usart, int data)
Send formatted integer using blocking/polling method (no IRQ nor DMA)
Definition at line 87 of file usart.c.
Referenced by usart_blocking_float(), and usart_blocking_tm().
void usart_blocking_int_zp (struct usart * usart, int data, int dp)
Send a formatted int with zeropadding using blocking/polling method (no IRQ nor DMA)
Parameters
usart Pointer to USART device
data Integer value to format and send
dp Number of digits to use
Definition at line 111 of file usart.c.
Referenced by usart_blocking_float(), and usart_blocking_tm().
void usart_blocking_send (struct usart * usart, volatile void * data, int length)
Send data using blocking/polling method (no IRQ nor DMA)
Definition at line 68 of file usart.c.
void usart_blocking_strz (struct usart * usart, volatile char * ptr)
Send zero terminated string using blocking/polling method (no IRQ nor DMA)
Definition at line 79 of file usart.c.
Referenced by report_msg_note().
void usart_configure_gpio (struct usart * usart)
Configure USART GPIO default values.
Definition at line 21 of file usart.c.
References DEFAULT.
Referenced by usart_init().
void usart_init (struct usart * usart, enum hw_init_state state)
Init usart device.
Todo:
Check if we are inited already
Definition at line 35 of file usart.c.
References HW_INIT_POST_INIT, HW_INIT_PRE_NVIC, HW_INIT_RCC, usart_configure_gpio(), and usart_set_defaults().
Referenced by hw_init_state().
void usart_set_defaults (struct usart * usart)
Configure USART to default values.
Definition at line 9 of file usart.c.
References DEFAULT.
Referenced by usart_init().