Irrigation test system 1: src/ws2812.c File Reference
ws2812.c File Reference
Implementation of WS2812 HAL.
#include "ws2812.h"
Functions
void ws2812_configure_timer (struct ws2812 *led)
Apply default configuration to the timer.
void ws2812_configure_gpio (struct ws2812 *led)
Apply default configuration to GPIO.
void ws2812_set_defaults (struct ws2812 *led)
Apply default configration to ws2812.
void ws2812_init (struct ws2812 *led, enum hw_init_state state)
Initiate ws2812 bus to state.
void ws2812_process_buffer (struct ws2812 *led)
Process LED buffer.
void ws2812_update (struct ws2812 *led)
Send data to LEDs.
void ws2812_update_blocking (struct ws2812 *led)
Send data to LEDs, wait for completion.
void ws2812_set_led (struct ws2812 *led, int index, int r, int g, int b)
Set LED buffer index to color r, g, b (0-255)
Detailed Description
Implementation of WS2812 HAL.
Definition in file ws2812.c.
Function Documentation
void ws2812_configure_gpio (struct ws2812 * led)
Apply default configuration to GPIO.
Parameters
led Bus to use
Definition at line 22 of file ws2812.c.
References ws2812::configuration, DEFAULT, and ws2812_config::pin.
Referenced by ws2812_init().
void ws2812_configure_timer (struct ws2812 * led)
Apply default configuration to the timer.
Parameters
led Bus to use
Definition at line 15 of file ws2812.c.
References ws2812_config::ccr, ws2812::configuration, DEFAULT, and ws2812_config::frequency.
Referenced by ws2812_init().
void ws2812_init (struct ws2812 * led, enum hw_init_state state)
Initiate ws2812 bus to state.
Parameters
led Bus to init
state New HW state
Definition at line 40 of file ws2812.c.
References ws2812_config::ccr, ws2812::configuration, HW_INIT_GPIO, HW_INIT_POST_INIT, HW_INIT_PRE_NVIC, ws2812_config::pin, timer_ccr_init(), ws2812_configure_gpio(), ws2812_configure_timer(), and ws2812_set_defaults().
Referenced by hw_init_state().
void ws2812_process_buffer (struct ws2812 * led)
Process LED buffer.
Definition at line 65 of file ws2812.c.
References ws2812_rgb::b, ws2812_config::bit0, ws2812_config::bit1, ws2812::configuration, ws2812_rgb::g, ws2812::led_buffer, ws2812::led_count, ws2812::pwm_buffer, and ws2812_rgb::r.
Referenced by ws2812_update(), and ws2812_update_blocking().
void ws2812_set_defaults (struct ws2812 * led)
Apply default configration to ws2812.
Parameters
led Bus to use
Definition at line 30 of file ws2812.c.
References ws2812_config::bit0, ws2812_config::bit1, ws2812::configuration, DEFAULT, and ws2812_config::frequency.
Referenced by ws2812_init().
void ws2812_set_led (struct ws2812 * led, int index, int r, int g, int b)
Set LED buffer index to color r, g, b (0-255)
Definition at line 96 of file ws2812.c.
References ws2812_rgb::g, ws2812::led_buffer, and ws2812_rgb::r.
Referenced by set_status_color().
void ws2812_update (struct ws2812 * led)
Send data to LEDs.
Definition at line 80 of file ws2812.c.
References ws2812_config::ccr, ws2812::configuration, ws2812::led_count, ws2812::pwm_buffer, and ws2812_process_buffer().
void ws2812_update_blocking (struct ws2812 * led)
Send data to LEDs, wait for completion.
Definition at line 90 of file ws2812.c.
References ws2812_config::ccr, ws2812::configuration, ws2812::led_count, ws2812::pwm_buffer, and ws2812_process_buffer().
Referenced by set_status_color().